version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node@1.1.6
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  build:
    docker:
      - image: circleci/node@1.1.6
    steps:
      - node/with-cache:
          steps:
            - run: npm build
workflows:
    build:
      jobs:
        - test
        - build:
          requires:
          - test
